#!/bin/bash

python proxy_generator.py -c -i 20 -r lon1
python proxy_generator.py -c -i 5 -r sgp1
python proxy_generator.py -c -i 5 -r nyc1
python proxy_generator.py -c -i 5 -r tor1
python proxy_generator.py -c -i 5 -r sfo1
python proxy_generator.py -c -i 5 -r blr1
python proxy_generator.py -c -i 5 -r fra1
